### ISSUE TITLE
Prtholog search is not working

### ISSUE THREAD

**Issue by LPioL** [pantherdb/pantherapi-pyclient#5]
Hi,

I tried an ortholog search but it doesn't work:

Request URL - http://panthertest3.med.usc.edu:8083/services/oai/pantherdb/ortholog/matchortho?organism=9606&orthologType=LDO&targetOrganism=10090,7227&geneInputList=AATK,ACIN1,ACTC1,ADAM17,ADAMTSL4
Traceback (most recent call last):
  File "pthr_go_annots.py", line 225, in <module>
    response = request.call_service()
  File "pthr_go_annots.py", line 33, in call_service
    return self.response_class(response.json())
  File "/home/skynet/Bureau/2021_NE_OverlapGenesMorphoCognitionAging/GO_simple_overlapping/pantherapi-pyclient/env/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/skynet/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/skynet/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/skynet/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any help ?

**Comment by mugitty** [comment]
@LPioL, please use pantherdb.org instead of panthertest3.  So the URL will become  http://pantherdb.org/services/oai/pantherdb/ortholog/matchortho?organism=9606&orthologType=LDO&targetOrganism=10090,7227&geneInputList=AATK,ACIN1,ACTC1,ADAM17,ADAMTSL4

**Comment by LPioL** [comment]
Thanks you should update pthr_go_annots.py.
